heat_template_version: 2017-09-01

description: Hashicorp tools deployment

#######################################################
# Parameters
parameters:
    image_id:
        type: string
        description: Operating system image to use
        default: ubuntu18.04_server
        constraints:
            - custom_constraint: glance.image

    front_net_id:
        type: string
        description: Network ID to use for the appliance
        constraints:
            - custom_constraint: neutron.network

    back_net_id:
        type: string
        description: Network ID to use for the appliance
        constraints:
            - custom_constraint: neutron.network

    os_username:
        type: string
        description: Cloud username for some internal batches

    os_password:
        type: string
        description: Cloud password for some internal batches
        hidden: true

    os_auth_url:
        type: string
        description: Cloud auth URL

    git_repo_url:
        type: string
        description: cloud-appliance-management repo
        default: https://github.com/mgrzybek/cloud-appliance-management

    git_repo_checkout:
        type: string
        description: branch/tag/commit to use
        default: master

    git_repo_username:
        type: string
        description: username or token to use
        default:

    git_repo_password:
        type: string
        description: secret
        hidden: true
        default:

    default_secgroup_id:
        type: string
        description: Default security group to use
        constraints:
            - custom_constraint: neutron.security_group

    internet_http_proxy_url:
        type: string
        description: HTTP proxy

    internet_http_no_proxy:
        type: string
        description: Proxy skiplist

    static_hosts:
        type: string
        description: JSON array of host:ip tuples
        default:

    flavor:
        type: string
        description: Cloud flavor to use
        constraints:
            - custom_constraint: nova.flavor

    consul_dns_domain:
       type: string
       description: DNS domain used by Consul server

    consul_datacenter:
       type: string
       description: Datacenter name used by Consul server

    consul_encrypt:
        type: string
        description: Consul shared secret for cluster communication
        hidden: true
        constraints:
            - length: { min: 44, max: 44 }

resources:

#######################################################
# Startup script

    node_boot_script:
        type: OS::Heat::SoftwareConfig
        properties:
            config:
                str_replace:
                    params:
                        $internet_http_proxy_url: { get_param : internet_http_proxy_url }
                        $internet_http_no_proxy: { get_param : internet_http_no_proxy }
                        $static_hosts: { get_param: static_hosts }

                        $git_repo_checkout: { get_param: git_repo_checkout }
                        $git_repo_url: { get_param: git_repo_url }
                        $git_repo_username: { get_param: git_repo_username }
                        $git_repo_password: { get_param: git_repo_password }

                        $os_password: { get_param: os_password }
                        $os_username: { get_param: os_username }
                        $os_auth_url: { get_param: os_auth_url }

                        $consul_dns_domain: { get_param: consul_dns_domain }
                        $consul_datacenter: { get_param: consul_datacenter }
                        $consul_encrypt: { get_param: consul_encrypt }
                        
                        $appliance_back_port : { get_resource: appliance_back_port}
                    template: |
                        #!/bin/bash
                        set -x

                        # Proxy
                        export HTTPS_PROXY=$internet_http_proxy_url
                        export HTTP_PROXY=$internet_http_proxy_url
                        export NO_PROXY=$internet_http_no_proxy,127.0.0.1,localhost,0.0.0.0
                        export https_proxy=$internet_http_proxy_url
                        export http_proxy=$internet_http_proxy_url
                        export no_proxy=$internet_http_no_proxy,127.0.0.1,localhost,0.0.0.0

                        # Install required packages to start git-ops-based auto-configuratiom
                        if which yum > /dev/null 2>&1 ; then
                            sed -i 's/gpgcheck=1/gpgcheck=1\nproxy=_none_/g' /etc/yum.repos.d/centos.repo

                            if [ ! -z "$HTTP_PROXY" ] ; then
                                grep -q proxy= /etc/yum.conf || echo "proxy=$HTTP_PROXY" >> /etc/yum.conf
                            fi

                            yum install --assumeyes ansible git jq
                        else
                            apt update
                            apt -y install ansible git jq python3-swiftclient unzip
                        fi
                        
                        # DNS: Populate /etc/hosts
                        if [ ! -z "$static_hosts" ] ; then
                            echo $static_hosts > /tmp/static_hosts
                            cat /tmp/static_hosts \
                                | perl -pe 's/\[|\]|{|}//g' \
                                |  tr ',' '\n' \
                                | awk -F: '{print $2,$1}' \
                                | awk '{print $1,$2}' \
                                >> /etc/hosts
                        fi

                        # Configure ansible to work without an entire environment set
                        sed -i 's/~/\/root/' /etc/ansible/ansible.cfg
                        sed -i 's/^#remote_tmp/remote_tmp/' /etc/ansible/ansible.cfg
                        sed -i 's/^#local_tmp/remote_tmp/' /etc/ansible/ansible.cfg

                        # Create local facts folder
                        mkdir -p /etc/ansible/facts.d

                        # Clone the bootstrap git repository
                        export REPO_PATH=/root/appliance
                        export ETC_PATH=$REPO_PATH/etc
                        export PLAYBOOK=$REPO_PATH/management.appliance.playbook.yml

                        ## Set the Openstack credentials
                        export OS_AUTH_URL="$os_auth_url"
                        export OS_PROJECT_ID=$(awk -F'"' '/project_id/ {print $4}' /run/cloud-init/instance-data.json)
                        export OS_USER_DOMAIN_NAME="Default"
                        export OS_USERNAME="$os_username"
                        export OS_PASSWORD="$os_password"
                        export OS_REGION_NAME="RegionOne"
                        export OS_INTERFACE=public
                        export OS_IDENTITY_API_VERSION=3
                        
                        # Swift container
                        #export VAULT_CONTAINER=$vault_container
                        export VAULT_CONTAINER=vault

                        # Set Consul variables
                        export CONSUL_DNS_DOMAIN="$consul_dns_domain"
                        export CONSUL_DATACENTER="$consul_datacenter"
                        export CONSUL_BOOTSTRAP_EXPECT=1
                        export CONSUL_ENCRYPT="$consul_encrypt"
                        
                        export BACK_IP=$(openstack port show $appliance_back_port -c fixed_ips -f json | jq '.fixed_ips[0].ip_address' | awk '{gsub("\"","");print}')

                        # Autoconf the appliance
                        ip link show
                        ip r
                        while curl -qs $git_repo_url ; do sleep 10 ; done
                        if [ ! -z "$git_repo_username$git_repo_password" ] ; then
                            auth_git_repo_url=$(echo $git_repo_url | awk -F// -v user=$git_repo_username  -v password=$git_repo_password '{print $1"//"user":"password"@"$2}')
                            git clone -b $git_repo_checkout $auth_git_repo_url $REPO_PATH || exit 1
                        else
                            git clone -b $git_repo_checkout $git_repo_url $REPO_PATH || exit 1
                        fi
                        . $REPO_PATH/management.appliance.autoconf.sh

                        # Stop secure shell
                        systemctl stop ssh
                        systemctl disable ssh

#######################################################
# Security group

    management_appliance_secgroup:
        type: OS::Neutron::SecurityGroup
        properties:
            description: Security group with webservices ports
            name: management-appliance
            rules: [
                {
                    protocol: tcp,
                    port_range_min: 8200,
                    port_range_max: 8200,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: ingress
                },
                {
                    protocol: tcp,
                    port_range_min: 8300,
                    port_range_max: 8300,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: ingress
                },
                {
                    protocol: tcp,
                    port_range_min: 8300,
                    port_range_max: 8300,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: egress
                },
                {
                    protocol: udp,
                    port_range_min: 8300,
                    port_range_max: 8300,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: ingress
                },
                {
                    protocol: udp,
                    port_range_min: 8300,
                    port_range_max: 8300,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: egress
                },
                {
                    protocol: tcp,
                    port_range_min: 8301,
                    port_range_max: 8301,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: ingress
                },
                {
                    protocol: tcp,
                    port_range_min: 8301,
                    port_range_max: 8301,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: egress
                },
                {
                    protocol: udp,
                    port_range_min: 8301,
                    port_range_max: 8301,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: ingress
                },
                {
                    protocol: udp,
                    port_range_min: 8301,
                    port_range_max: 8301,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: egress
                },
                {
                    protocol: tcp,
                    port_range_min: 8302,
                    port_range_max: 8302,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: ingress
                },
                {
                    protocol: tcp,
                    port_range_min: 8302,
                    port_range_max: 8302,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: egress
                },
                {
                    protocol: tcp,
                    port_range_min: 8500,
                    port_range_max: 8500,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: ingress
                },
                {
                    protocol: tcp,
                    port_range_min: 8600,
                    port_range_max: 8600,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: ingress
                }
            ]

#######################################################
# Appliance

    appliance_front_port:
        type: OS::Neutron::Port
        properties:
            network_id: { get_param: front_net_id }
            security_groups: [
                { get_param: default_secgroup_id }
            ]

    appliance_back_port:
        type: OS::Neutron::Port
        properties:
            network_id: { get_param: back_net_id }
            security_groups: [
                { get_param: default_secgroup_id },
                { get_resource: management_appliance_secgroup }
            ]

    appliance:
        type: OS::Nova::Server
        properties:
            name: management
            image: { get_param: image_id }
            flavor: { get_param: flavor }
            networks:
                - port: { get_resource: appliance_front_port }
                - port: { get_resource: appliance_back_port }
            metadata: {
                group: management,
                image: { get_param: image_id }
            }
            user_data_format: SOFTWARE_CONFIG
            user_data: { get_resource: node_boot_script }

#    vault_swift:
#        type: OS::Swift::Container
#        properties:
#            name: vault

#######################################################
# Outputs

outputs:

    appliance_front_port:
        description: Front port ID of the appliance
        value: { get_resource: appliance_front_port }
